# Generated by Django 4.0.3 on 2022-06-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_collection', models.CharField(choices=[('coding_book', 'coding_book'), ('hacking_book', 'hacking_book'), ('history_book', 'history_book'), ('general_knowledge', 'general_knowledge')], max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=100)),
                ('book_des', models.TextField()),
                ('book_image', models.ImageField(upload_to='book_image/')),
                ('admin_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
        ),
    ]
